### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by shzxm** [blueset/efb-telegram-master#101]
登陆时出现问题

Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/ehforwarderbot/__main__.py", line 277, in main
    init(conf)
  File "/usr/local/lib/python3.8/dist-packages/ehforwarderbot/__main__.py", line 91, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/local/lib/python3.8/dist-packages/efb_wechat_slave/__init__.py", line 157, in __init__
    self.authenticate('console_qr_code', first_start=True)
  File "/usr/local/lib/python3.8/dist-packages/efb_wechat_slave/__init__.py", line 668, in authenticate
    self.bot.enable_puid(
  File "/usr/local/lib/python3.8/dist-packages/efb_wechat_slave/vendor/wxpy/api/bot.py", line 181, in enable_puid
    self.puid_map = PuidMap(path, puid_logs)
  File "/usr/local/lib/python3.8/dist-packages/efb_wechat_slave/vendor/wxpy/utils/puid_map.py", line 114, in __init__
    self.load()
  File "/usr/local/lib/python3.8/dist-packages/efb_wechat_slave/vendor/wxpy/utils/puid_map.py", line 263, in load
    self.user_names, self.wxids, self.remark_names, self.captions = pickle.load(fp)
EOFError: Ran out of input

文件我已经检查.
也已经更新过了

/usr/local/lib/python3.8/dist-packages/efb_wechat_slave/vendor/wxpy/utils/puid_map.py

文件不为空
文件内容
[puid_map.txt](https://github.com/blueset/efb-telegram-master/files/4602830/puid_map.txt)

**Comment by shzxm** [comment]
已经重装过一次系统了.只有安装完的第一次可以正常使用.
之后关闭重新开启就会出现这个问题
