### ISSUE TITLE
Unable to send gif animation in telegram

### ISSUE THREAD

**Issue by imguoguo** [blueset/efb-telegram-master#14]
I saw the following in the log file when I tried to send gif animation. Can someone explain what is wrong? Running ehForwarderBot on Ubuntu 17.04.
```
2018-04-01 18:24:15,251 [ERROR]: telegram.ext.dispatcher (dispatcher.process_update; dispatcher.py:301) 
    An uncaught error was raised while processing the update
  File "/usr/local/lib/python3.6/dist-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/usr/local/lib/python3.6/dist-packages/moviepy/video/VideoClip.py", line 491, in write_gif
    dispose=dispose, colors=colors)
  File "<decorator-gen-12>", line 2, in write_gif
  File "/usr/local/lib/python3.6/dist-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-11>", line 2, in write_gif
  File "/usr/local/lib/python3.6/dist-packages/moviepy/decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "/usr/local/lib/python3.6/dist-packages/moviepy/video/io/gif_writers.py", line 184, in write_gif
    '-r', "%.02f"%fps, filename], **popen_params)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not _TemporaryFileWrapper
2018-04-01 18:24:15,251 [ERROR]: telegram.ext.dispatcher (dispatcher.process_update; dispatcher.py:301)
    An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.6/dist-packages/telegram/ext/messagehandler.py", line 169, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/master_message.py", line 70, in msg_thread_creator
    threading.Thread(target=self.msg, args=(bot, update)).run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/master_message.py", line 108, in msg
    return self.process_telegram_message(bot, update)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/master_message.py", line 325, in process_telegram_message
    m.file, m.mime, m.filename, m.path = self._download_gif(message.document)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/master_message.py", line 440, in _download_gif
    VideoFileClip(path).write_gif(gif_file, program="ffmpeg")
  File "<decorator-gen-56>", line 2, in write_gif
  File "/usr/local/lib/python3.6/dist-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-55>", line 2, in write_gif
  File "/usr/local/lib/python3.6/dist-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/usr/local/lib/python3.6/dist-packages/moviepy/video/VideoClip.py", line 491, in write_gif
    dispose=dispose, colors=colors)
  File "<decorator-gen-12>", line 2, in write_gif
  File "/usr/local/lib/python3.6/dist-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-11>", line 2, in write_gif
  File "/usr/local/lib/python3.6/dist-packages/moviepy/decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "/usr/local/lib/python3.6/dist-packages/moviepy/video/io/gif_writers.py", line 184, in write_gif
    '-r', "%.02f"%fps, filename], **popen_params)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not _TemporaryFileWrapper
```

**Comment by wolfsilver** [comment]
同样遇到这个问题

**Comment by wolfsilver** [comment]
![image](https://user-images.githubusercontent.com/2452450/40539803-7a4b73e8-6048-11e8-8950-c5ea858912b1.png)
可以解决
