### ISSUE TITLE
This mistake happened when wechat logining successful

### ISSUE THREAD

**Issue by Fagurio** [blueset/efb-telegram-master#21]
And efb_telegram_master seems goes wrong,I don't know how to slove this

Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 11, in <module>    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 190, in main                               init()
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 94, in init
    (instance_id=instance_id))                                File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/__init__.py", line 126, in __init__
    self.voice_recognition: VoiceRecognitionManager = VoiceRecognitionManager(self)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/voice_recognition.py", line 49, in __init__
    self.voice_engines.append(BaiduSpeech(self.channel, tokens['baidu']))
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/voice_recognition.py", line 116, in __init__
    "client_id": key_dict['api_key'],
TypeError: 'NoneType' object is not subscriptable

**Comment by Fagurio** [comment]
so sorry I fixed it by rewrite the ETM configure file
