### ISSUE TITLE
I got the following error after restarting the host.

### ISSUE THREAD

**Issue by scarletsakuya** [blueset/efb-telegram-master#30]
I got the following error after restarting the host.Before that it works fine.
The error is about missing ffmpeg ? But I have installed it.
 
root@:~# cat /etc/debian_version
9.5
root@:~# uname -a
Linux xx-vm 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u5 (2018-09-30) x86_64 GNU/Linux

root@:~# apt-get install ffmpeg
Reading package lists... Done
Building dependency tree
Reading state information... Done
ffmpeg is already the newest version (7:3.2.12-1~deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

root@:~# ehforwarderbot
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 202, in main
    init()
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 75, in init
    conf = config.load_config()
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/config.py", line 33, in load_config
    channel = utils.locate_module(data['master_channel'], 'master')
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/utils.py", line 134, in locate_module
    return i.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/__init__.py", line 27, in <module>
    from .master_message import MasterMessageProcessor
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/master_message.py", line 13, in <module>
    from moviepy.video.io.VideoFileClip import VideoFileClip
  File "/usr/local/lib/python3.6/dist-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.video.VideoClip import VideoClip
  File "/usr/local/lib/python3.6/dist-packages/moviepy/video/VideoClip.py", line 18, in <module>
    from ..config import get_setting
  File "/usr/local/lib/python3.6/dist-packages/moviepy/config.py", line 35, in <module>
    FFMPEG_BINARY = get_exe()
  File "/usr/local/lib/python3.6/dist-packages/imageio/plugins/ffmpeg.py", line 127, in get_exe
    "Need ffmpeg exe. "
imageio.core.fetching.NeedDownloadError: Need ffmpeg exe. You can obtain it with either:
  - install using conda: conda install ffmpeg -c conda-forge
  - download using the command: imageio_download_bin ffmpeg
  - download by calling (in Python): imageio.plugins.ffmpeg.download()

**Comment by blueset** [comment]
Please check if you have `ffmpeg` in your `$PATH` running EFB framework.

**Comment by Lienhsini** [comment]
百度语音识别出现如下错误

2018-12-10 05:51:54,949 [ERROR]: telegram.ext.dispatcher (dispatcher.process_update; dispatcher.py:301)
    An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.6/dist-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/voice_recognition.py", line 76, in recognize_speech
    file, _, _ = self.bot.download_file(update.message, update.message.reply_to_message.voice, MsgType.Audio)
AttributeError: 'TelegramBotManager' object has no attribute 'download_file'

感谢blueset

**Comment by blueset** [comment]
Please open another issue if you have something new to report.
