### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by blankde** [blueset/efb-telegram-master#50]
when I want to send message in my group, I get
![捕获](https://user-images.githubusercontent.com/11952914/55788867-bc088480-5aeb-11e9-8c89-0b2d305fa45a.PNG)

when I pick one of my contact, the log shows:

```
2019-04-09 09:05:37,715 [ERROR]: telegram.ext.dispatcher (dispatcher.process_update; dispatcher

.py:301)
    An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.6/dist-packages/telegram/ext/conversationhandler.py", line 305, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/usr/local/lib/python3.6/dist-packages/telegram/ext/callbackqueryhandler.py", line 143, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/chat_binding.py", line 822, in suggested_recipient
    chat = self.msg_storage[storage_id].candidates[int(param.split(' ', 1)[1])]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by blankde** [comment]
it seems the problem happens in chat_binding.py, line 323
`chat_list = self.msg_storage[storage_id] = ChatListStorage(chats, offset)`

in the  initialize function of ChatListStorage, it sets the **candidates** to be None

so
`chat = self.msg_storage[storage_id].candidates[int(param.split(' ', 1)[1])]`
will report that **candidates**  is NoneType.

**Comment by blueset** [comment]
Thank you for the bug report. This will be fixed in the next version.

**Comment by blueset** [comment]
Fixed.
