### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by blueset** [blueset/efb-telegram-master#6]
_From @Gontid on July 27, 2017 14:31_

Doesn't seem to affect functionality but I saw the following in the log file. Can someone explain what is wrong? Running ehForwarderBot on Centos 7.

```
return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/lib/python3.6/site-packages/peewee.py", line 3775, in execute_sql
    self.commit()
  File "/usr/lib/python3.6/site-packages/peewee.py", line 3598, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/lib/python3.6/site-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/peewee.py", line 3768, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: database is locked
```

Appreciate your help!

_Copied from original issue: blueset/ehForwarderBot#68_

**Comment by blueset** [comment]
Can you reproduce this error? If so, what are the steps to reproduce it?

**Comment by blueset** [comment]
_From @Gontid on August 8, 2017 9:46_

It shows up immediately after QR code is scanned and WeChat login is complete.

**Comment by blueset** [comment]
_From @LiCongrui on August 8, 2017 15:12_

I am the same problem, when I use "/chat" to send a wechat message.

**Comment by blueset** [comment]
Please ensure that there are no other process using `tgdata.db` before EFB is started, and ensure that EFB process has the permission to access that file.

**Comment by blueset** [comment]
_From @lyckyercyber on September 7, 2017 16:15_

same issue here
same trigger as 'I am the same problem, when I use "/chat" to send a wechat message.'
I'm sure 'there are no other process using tgdata.db before EFB is started, and ensure that EFB process has the permission to access that file.'

**Comment by blueset** [comment]
_From @ddqp on November 30, 2017 9:29_

same issue here,

**Comment by blueset** [comment]
As I cannot reproduce in my environment, I would like to seek help to those who can reproduce this issue stably.

**Comment by 7nights** [comment]
Same problem here... Any suggestions to solve this issue?

**Comment by yi-ji** [comment]
same problem here too

To reproduce: /link or /chat, e.g.

```
Traceback (most recent call last):
  File "/home/jiy/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/home/jiy/.local/lib/python3.6/site-packages/telegram/ext/messagehandler.py", line 169, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/home/jiy/.local/lib/python3.6/site-packages/efb_telegram_master/master_message.py", line 70, in msg_thread_creator
    threading.Thread(target=self.msg, args=(bot, update)).run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jiy/.local/lib/python3.6/site-packages/efb_telegram_master/master_message.py", line 88, in msg
    assocs = self.db.get_chat_assoc(master_uid=utils.chat_id_to_str(self.channel_id, message.chat.id))
  File "/home/jiy/.local/lib/python3.6/site-packages/efb_telegram_master/db.py", line 140, in get_chat_assoc
    if len(slaves) > 0:
  File "/home/jiy/.local/lib/python3.6/site-packages/peewee.py", line 1688, in __len__
    self._ensure_execution()
  File "/home/jiy/.local/lib/python3.6/site-packages/peewee.py", line 1670, in _ensure_execution
    self.execute()
  File "/home/jiy/.local/lib/python3.6/site-packages/peewee.py", line 1587, in inner
    return method(self, database, *args, **kwargs)
  File "/home/jiy/.local/lib/python3.6/site-packages/peewee.py", line 1658, in execute
    return self._execute(database)
  File "/home/jiy/.local/lib/python3.6/site-packages/peewee.py", line 1809, in _execute
    cursor = database.execute(self)
  File "/home/jiy/.local/lib/python3.6/site-packages/peewee.py", line 2666, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/home/jiy/.local/lib/python3.6/site-packages/peewee.py", line 2660, in execute_sql
    self.commit()
  File "/home/jiy/.local/lib/python3.6/site-packages/peewee.py", line 2451, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/jiy/.local/lib/python3.6/site-packages/peewee.py", line 178, in reraise
    raise value.with_traceback(tb)
  File "/home/jiy/.local/lib/python3.6/site-packages/peewee.py", line 2653, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: database is locked
```

**Comment by blueset** [comment]
Marking as stale as no update in the past year.

**Comment by BillScott1024** [comment]
出现了相同的报错日志，  文字，图片信息可以接受，文件无法接受转发，报错日志如下：

![image](https://user-images.githubusercontent.com/22955480/167259592-76056b0c-1237-4cd7-9edc-992fdbb1c5e0.png)
