### ISSUE TITLE
some bugs reported from ehforwarderbot

### ISSUE THREAD

**Issue by NavePnow** [blueset/efb-telegram-master#92]
```
AttributeError("type object 'MsgLog' has no attribute 'get_or_none'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/efb_telegram_master/slave_message.py", line 116, in send_message
    self.dispatch_message(msg, msg_template, old_msg_id, tg_dest, silent)
  File "/usr/local/lib/python3.7/site-packages/efb_telegram_master/slave_message.py", line 220, in dispatch_message
    self.db.add_or_update_message_log(etm_msg, tg_msg, old_msg_id)
  File "/usr/local/lib/python3.7/site-packages/efb_telegram_master/db.py", line 401, in add_or_update_message_log
    r = MsgLog.get_or_none(MsgLog.master_msg_id == master_msg_id)
AttributeError: type object 'MsgLog' has no attribute 'get_or_none'
```

**Comment by blueset** [comment]
This method does exist on Peewee ([API docs](http://docs.peewee-orm.com/en/latest/peewee/api.html#Model.get_or_none)). I couldn't reproduce this on my local environment.

Can you try to upgrade your `peewee` and see if the issue persists?

**Comment by NavePnow** [comment]
after upgrading peewee, the problem solved. Thx bro
